/** Códigos de demora (COD DLY) para MVT — valor almacenado = código numérico como string */
export interface DelayCodeOption {
    code: string;
    label: string;
}

export const DELAY_CODE_OPTIONS: DelayCodeOption[] = [
    { code: "1", label: "DEFAULT CODE" },
    { code: "2", label: "DELAY due to MOTION/ITC (Base)" },
    { code: "3", label: "DELAY OR LACK OF BUSES" },
    { code: "4", label: "LATE OR INCORRECT AIRCRAFT ROTATION" },
    { code: "5", label: "NATURAL DISASTER" },
    { code: "6", label: "NO GATE/STAND AVAILABILITY DUE TO OWN AIRLINE ACTIVITY" },
    { code: "7", label: "LATE ARRIVAL OF CREW BY SUPPLIER" },
    { code: "8", label: "PAX DISRUPTIVE" },
    { code: "9", label: "SCHEDULED GROUND TIME LESS THAN DECLARED MINIMUM GROUND TIME" },
    { code: "10", label: "REACTIONARY AIRPORT" },
    { code: "11", label: "LATE CHECK-IN" },
    { code: "12", label: "LATE CHECK-IN" },
    { code: "14", label: "OVERSALES" },
    { code: "15", label: "BOARDING" },
    { code: "18", label: "BAGGAGE PROCESSING" },
    { code: "19", label: "REDUCED MOBILITY" },
    { code: "20", label: "REACTIONARY OTHERS" },
    { code: "23", label: "LATE ACCEPTANCE" },
    { code: "30", label: "REACTIONARY AIRPORT (EXTERNO)" },
    { code: "31", label: "AIRCRAFT DOCUMENTATION LATE/INACCURATE" },
    { code: "33", label: "LOADING EQUIPMENT" },
    { code: "34", label: "SERVICING EQUIPMENT" },
    { code: "35", label: "AIRCRAFT CLEANING" },
    { code: "36", label: "FUELLING/DEFUELLING" },
    { code: "37", label: "CATERING" },
    { code: "38", label: "FUEL SERVICE LOSS OF PRIORITY" },
    { code: "39", label: "TECHNICAL EQUIPMENT" },
    { code: "40", label: "REACTIONARY MAINTENANCE" },
    { code: "41", label: "AIRCRAFT DEFECTS" },
    { code: "42", label: "SCHEDULED MAINTENANCE" },
    { code: "46", label: "AIRCRAFT CHANGE" },
    { code: "50", label: "REACTIONARY DAMAGE TO AIRCRAFT" },
    { code: "51", label: "DAMAGE DURING FLIGHT OPERATIONS" },
    { code: "52", label: "DAMAGE DURING GROUND OPERATIONS" },
    { code: "53", label: "AIRCRAFT CHANGE due in FLIGHT DAMAGE" },
    { code: "54", label: "AIRCRAFT CHANGE due on GROUND DAMAGE" },
    { code: "55", label: "AIRPORT LOCAL SYSTEM / HARDWARE FAILURE" },
    { code: "57", label: "FLIGHT PLAN" },
    { code: "58", label: "OTHER AUTOMATED SYSTEM" },
    { code: "59", label: "REACTIONARY IT OPS" },
    { code: "60", label: "REACTIONARY CREW" },
    { code: "61", label: "FLIGHT PLAN" },
    { code: "62", label: "TRAINING / INSPECTION FLIGHT" },
    { code: "63", label: "LATE CREW BOARDING OR DEPARTURE PROCEDURES" },
    { code: "64", label: "FLIGHT DECK CREW SHORTAGE" },
    { code: "65", label: "FLIGHT DECK CREW SPECIAL REQUEST" },
    { code: "66", label: "LATE CABIN CREW BOARDING OR DEPARTURE PROCEDURES" },
    { code: "67", label: "CABIN CREW SHORTAGE" },
    { code: "68", label: "CABIN CREW ERROR OR SPECIAL REQUEST" },
    { code: "69", label: "CAPTAIN REQUEST FOR SECURITY CHECK" },
    { code: "70", label: "REACTIONARY WEATHER" },
    { code: "71", label: "DEPARTURE STATION" },
    { code: "72", label: "DESTINATION STATION" },
    { code: "73", label: "EN ROUTE OR ALTERNATE" },
    { code: "75", label: "DE-ICING OF AIRCRAFT" },
    { code: "76", label: "REMOVAL OF SNOW, ICE, WATER AND SAND FROM AIRPORT" },
    { code: "77", label: "GROUND HANDLING IMPAIRED BY ADVERSE WEATHER CONDITIONS" },
    { code: "80", label: "REACTIONARY ATC" },
    { code: "81", label: "ATFM due to ATC EN-ROUTE DEMAND/CAPACITY." },
    { code: "82", label: "ATFM due to ATC STAFF/EQUIPMENT EN-ROUTE." },
    { code: "83", label: "ATFM due to RESTRICTION AT DESTINATION AIRPORT." },
    { code: "84", label: "ATFM due to GDP/FLOW CONTROL" },
    { code: "85", label: "MANDATORY SECURITY" },
    { code: "86", label: "IMMIGRATION, CUSTOMS, HEALTH" },
    { code: "87", label: "AIRPORT FACILITIES" },
    { code: "88", label: "RESTRICTIONS AT AIRPORT OF DESTINATION." },
    { code: "89", label: "RESTRICTIONS AT AIRPORT OF DEPARTURE WITH OR WITHOUT ATFM RESTRICTIONS." },
    { code: "90", label: "REACTIONARY PLANNING" },
    { code: "91", label: "PASSENGER/BAGGAGE CONNECTION" },
    { code: "92", label: "COMMERCIAL / PRE-OPERATIONAL PROCESS ERROR" },
    { code: "93", label: "REACTIONARY SOC" },
    { code: "94", label: "FLIGHT CREW ROTATION" },
    { code: "95", label: "CABIN CREW ROTATION" },
    { code: "96", label: "OPERATIONS CONTROL" },
    { code: "97", label: "INDUSTRIAL ACTION WITH OWN AIRLINE" },
    { code: "98", label: "INDUSTRIAL ACTION OUTSIDE OWN AIRLINE" },
    { code: "99", label: "OTHER REASON" },
].sort((a, b) => Number(a.code) - Number(b.code));

export function formatDelayOption(o: DelayCodeOption): string {
    return `${o.code}: ${o.label}`;
}
