export const pdfData = [
  { flt: "3018", text: "Cambio de matricula a las 02AM. Aeronave en 05. 03:30 se coordinó cruce. Demora en el cruce por tránsito en 11. 04:30 llega avión a comercial. Se pierde prioridad en fuel. ATO --> Gestionar AIMS para EZE." },
  { flt: "3039", text: "Se gestiono nuevo formato de briefing para entrega a crew con firmas de ambas áreas con hitos de inicio y fin de embarque. Adicional se suman bagtag de equipajes de mano para los equipajes de cabina." },
  { flt: "3880", text: "CREW SOLICITA SANIDAD PARA PAX. SANIDAD ATIENDE A PAX ABORDO Y PERMITE SEGUIR" },
  { flt: "3201", text: "ITC con simultaneidad llega 10 minutos tarde por falta de personal. ITC trabajando con 2 cintas." },
  { flt: "3505", text: "PAX se sienta al lado de su acompañante. CREW solicito que se cambie de asiento. No se quiso mover y se freno el embarque hasta que se cambio de asiento. PAX trata mal a crew y quería filmar. Revisar con crew. SIN INTERVENCIÓN DE PSA." },
  { flt: "3041", text: "LLEGADA DE DIRECTIVO DE FMI. CERRADAS LAS CALLES DE SERVICIO IMPIDE TRASLADO DE PAX." },
  { flt: "3040", text: "ATO SATURADO POR CIERRE DEL DOMINGO 26/07. SE UTILIZA PLATAFORMA AUXILIAR PARA POSICIONAR AERONAVES HASTA LIBERAR PLATAFORMA PRINCIPAL." },
  { flt: "3046", text: "POS 8 - MANGA FUERA DE SERVICIO. SE DESEMBARCA POR UNA SOLA ESCALERA. MANTO ACTIVADO PARA REVISIÓN DE MANGA POSTERIOR AL DESEMBARQUE SE PROBO PONER MANGA PERO NO FUNCIONÓ. SE EMBARCA POR ESCALERA." },
  { flt: "3192", text: "NECESARIO RECODIFICAR POR ITINERARIO." },
  { flt: "3161", text: "Aviso a HCC de horario de asignación de puerta para poder hacer reclamos a AA. Horario de asignación:" },
  { flt: "3042", text: "SATURACIÓN DE ATO POR CONTINGENCIA DEL DOMINGO 26/07. REVISAR CON SOC LA INFORMACIÓN DE CREW EN VUELOS CONTINGENCIA." },
  { flt: "3076", text: "Perdida de SLOT por reprogramación de vuelo." },
  { flt: "3047", text: "Aviso a HCC de horario de asignación de puerta para poder hacer reclamos a AA. Horario de asignación:" },
  { flt: "3144", text: "Fallas en acomodación de familias. PAX no detallados como Child y sistema no acomoda. Desde check-in se acomodan aquellas familias que se presentan. WEB CHECK-IN PROBLEMA." },
  { flt: "3055", text: "Aviso a HCC de horario de asignación de puerta para poder hacer reclamos a AA. Horario de asignación:" },
  { flt: "3182", text: "AMBOS VUELOS DLY GENERA SUPERPOSICIÓN EN PLATAFORMA." },
  { flt: "3077", text: "ATC AUTORIZA PRIMERO 3083 // ITC CON 2 PERSONAS." },
  { flt: "3052", text: "Jefe escala se reunirá con concesionario para revisar la situación" },
  { flt: "3048", text: "Jefe escala se reunirá con concesionario para revisar la situación" },
  { flt: "3781", text: "SOC baja NI-2. Sin info clara a PAX altera la situación. AA pone en tams organismos salida a las 23hs y pax veian esta info en las pantallas. ACTVIACIÓN PSA PENDIENTE DE CONFIRMAR." },
  { flt: "3056", text: "VUELOS OBVK SIN POSIBILIDAD DE ACOMODAR FAMILIAS. REVISAR CON M.CAMPOS Y CPP COMO PASAN FAMILIAS EN REPROGRAMACIONES." },
  { flt: "3110", text: "REVISIÓN HCC" },
  { flt: "3163", text: "Aviso a HCC de horario de asignación de puerta para poder hacer reclamos a AA. Horario de asignación:" },
  { flt: "3111", text: "REVISAR CON CREW INFGRESO DE FAMILIAS A CABINA PARA FOTOS. DESDE ATO SE EMBARCA POR 2 PUERTAS Y CON PREEMBARQUE EN FILA. DLY 10 MIN DE ACUMULACIÓN EN MANGA." },
  { flt: "3234", text: "FALTA DE TENSER: CONFIRMAR FECHA DE VUELTA A SERVICIO" },
  { flt: "3058", text: "CAMBIO DE WX REPENTINO OBLIGA A REALIZAR DE-ICING. CAMIÓN NO ESTABA LISTO PARA EL PROCESO." },
  { flt: "3064", text: "FALTA DE TENSER: CONFIRMAR FECHA DE VUELTA A SERVICIO" },
  { flt: "3054", text: "VUELOS OBVK SIN POSIBILIDAD DE ACOMODAR FAMILIAS. REVISAR CON M.CAMPOS Y CPP COMO PASAN FAMILIAS EN REPROGRAMACIONES." },
  { flt: "3015", text: "CF 01:52 CONTROL DE LID REALIZADO. BRIEFING ENTREGADO. 65 BAGS" },
  { flt: "3050", text: "REVISAR CODIFICACIÓN, EL AVIÓN TUVO DE-ICING. SIMULTANEIDAD CON 3058." }
];
